spring:
  datasource:
    url: jdbc:postgresql://localhost:5001/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
